### PR TITLE
Add versionCode

### PR DESCRIPTION
**Pull request by Integral-Tech**
An incremental versionCode is required for F-droid app.
@guozhigq Don't forget to increase versionCode when releasing new versions (for example, update ```1.0.15+1015``` to ```1.0.16+1016```)
https://github.com/guozhigq/pilipala/issues/206#issuecomment-1873671976

### CODE REVIEW

**Comment by linsui** [comment]
If we want to publish splitted apks on F-Droid, different abi needs to have different version codes. See https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L105 for example.

**Comment by Integral-Tech** [comment]
@linsui abiCodes added.

**Comment by linsui** [comment]
All these lines are needed. https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L104-L114

**Comment by Integral-Tech** [comment]
> All these lines are needed. https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L104-L114

All lines added.

**Comment by linsui** [comment]
I didn't notice that, but why do you give the armeabi-v7a abi highest version code? It means arm64-v8a always install the armeabi-v7a apk because it has higher version code.

**Comment by Integral-Tech** [comment]
> I didn't notice that, but why do you give the armeabi-v7a abi highest version code? It means arm64-v8a always install the armeabi-v7a apk because it has higher version code.

Sorry, I mistakenly believe that smaller abiCode means higher priority.

Here is the fix PR: https://github.com/guozhigq/pilipala/pull/396

**Pull request merged**
